[package]
name = "json-core"
version = "0.1.0"
edition = "2021"

[dependencies]
#risc0-zkvm = { path = "../../../risc0/zkvm", default-features = false }
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
serde = "1.0"
