[package]
version = "0.1.0"
name = "ad-qualification-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
sp1-zkvm = "4.0.0"
ad-qualification-lib = { path = "../lib" }

