[package]
name = "eth_trifecta_2025"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
bytemuck_derive = "=1.8.1"
